#!/usr/bin/env bash

set -e

static_src=../photo-header/client/dist

if [[ $# -ne 1 ]]; then
    echo "Usage: build TAG"
    exit 1
else
    tag="$1"
fi

if [[ ! -d "$static_src" ]]; then
    echo "Directory does not exist: $static_src"
    exit 1
fi

rm -rf ./static
cp -r "$static_src" ./static

docker build -t $tag .

# vi:syntax=sh
